#! /bin/bash
#    __
#   / /_  _________ _      ______ ___
#  / __ \/ ___/ __ \ | /| / / __ `__ \
# / /_/ (__  ) /_/ / |/ |/ / / / / / /
#/_.___/____/ .___/|__/|__/_/ /_/ /_/
#          /_/
#						https://github.com/sk1lax/bspwm-dots
#

#*****----- Workspaces -----*****
bspc monitor -d '1' '2' '3' '4' '5' '6' '7' '8' '9' &
#*****----- BSPWN Launch -----*****
export XDG_CURRENT_DESKTOP='bspwm'

sxhkd &
#feh --no-fehbg --bg-fill ~/Pictures/bg.png &
nitrogen --restore
picom &
plank &
lxpolkit &
flameshot &
alsa &
dunst -conf ~/.config/bspwm/dunstrc &
#xdotool search --name Plank windowraise &
#blueman-applet &
#nm-applet &
~/.config/bspwm/launch.sh &
#~/.config/bspwm/plank.sh &

#*****----- BSPWN Rules -----*****
bspc rule -a firefox center=true state=tiled &
#bspc rule -a firefox desktop='^2' follow=on
bspc rule -a TelegramDesktop state=floating center=true follow=on rectangle=485x1000+0+0
bspc rule -a gnome-calculator state=floating rectangle=374x488 &
bspc rule -a pavucontrol follow=on state=floating rectangle=800x400+1120+630 &
bspc rule -a SimpleScreenRecorder center=true  follow=on state=floating &
bspc rule -a vlc follow=on center=true state=floating &
bspc rule -a org.gnome.FileRoller follow=on center=true state=floating rectangle=500x700 &
bspc rule -a Viewnior state=floating center=true &
bspc rule -a "*:Alacritty:bluetui"  state=floating rectangle=800x600+1120+430 &
bspc rule -a "*:Alacritty:nmtui"  state=floating rectangle=1900x850 &
bspc rule -a nmtui state=floating rectangle=800x400+1120+630 &
bspc rule -a Blueman-manager state=floating rectangle=800x400+1120+630 &
#bspc rule -a plank layer=above manage=on border=off focus=off locked=on
#*****----- Window Gaps & Paddings -----*****
bspc config gapless_monocle false &
bspc config paddingless_monocle	 true &

bspc config window_gap 5 &
#*****----- Window Borders -----*****
bspc config border_width 1 &

bspc config focused_border_color "#3684dd"
bspc config active_border_color "#3684dd"
bspc config normal_border_color "#1f1f1f"

#bspc config presel_feedback_color "#"
#bspc config normal_borredshift-gtkder_color "#"
#*****----- Fix Pointer -----*****
xsetroot -cursor_name left_ptr &

#*****----- BSPWM Configs -----*****
bspc config focus_follows_pointer true &
bspc config pointer_modifier super &
bspc config pointer_action1 move &
bspc config pointer_action2 resize_side &
bspc config pointer_action3 resize_corner &
#*****----- Key to move/resize window -----*****
bspc config pointer_modifier	super &
#*****----- I dunno anything about these :d -----*****
bspc config single_monocle	     true &
bspc config borderless_monocle   false &
bspc config split_ratio          0.5 &

bspc config focus_follows_pointer true &

bspc config automatic_scheme          longest_side
bspc config initial_polarity          second_child
bspc config removal_adjustment        true
